name: Firebase App Distribution

on:
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run generator
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Flutter APK
        run: flutter build apk --release

      - name: List APK files
        run: ls -l ./build/app/outputs/flutter-apk/

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_DISTRIBUTION_KEY }}
          groups: flowery_tracking_testers
          file: ./build/app/outputs/flutter-apk/app-release.apk